# Generated by Django 5.2.6 on 2025-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='template_link',
            field=models.URLField(blank=True, help_text='Optional: Link to template (Canvas, Google Docs, etc.)'),
        ),
    ]
