# Generated by Django 5.2.6 on 2025-10-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_taskcategory_template_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategory',
            name='template_link',
        ),
    ]
