# Generated by Django 5.2.6 on 2025-10-13 12:06

import django.db.models.deletion
import task_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_taskcategory_template_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-print, fas fa-chart-line)', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Main image for this service category (recommended: 400x300px)', null=True, upload_to=task_manager.models.service_category_image_path)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover/banner image (recommended: 1200x400px)', null=True, upload_to=task_manager.models.service_category_image_path)),
                ('color', models.CharField(default='#4e73df', help_text='Hex color code for this category (e.g., #4e73df)', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'ordering': ['service_category', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Task Categories'},
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='estimated_duration',
            field=models.CharField(blank=True, help_text='e.g., 30 minutes, 2 hours, 1 day', max_length=50),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class for this specific service', max_length=50),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Service-specific image (recommended: 300x200px)', null=True, upload_to=task_manager.models.task_category_image_path),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard price for this service', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='task_manage_categor_f0bdbf_idx'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='task_manager.servicecategory'),
        ),
    ]
