# Generated by Django 5.2.6 on 2025-10-13 14:02

from django.db import migrations


from django.db import migrations

def create_default_service_category(apps, schema_editor):
    ServiceCategory = apps.get_model('task_manager', 'ServiceCategory')
    ServiceCategory.objects.create(
        id=1,
        name="General",
        description="General services",
        is_active=True
    )

def reverse_func(apps, schema_editor):
    ServiceCategory = apps.get_model('task_manager', 'ServiceCategory')
    ServiceCategory.objects.filter(id=1).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_servicecategory_alter_taskcategory_options_and_more'),
    ]

    operations = [
    ]
