# Generated by Django 5.2.6 on 2025-10-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_taskcategory_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='service_category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='task_manager.servicecategory'),
        ),
    ]
