# Generated by Django 5.2.6 on 2025-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
