# Generated by Django 5.2.6 on 2025-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
