# Generated by Django 5.2.6 on 2025-09-13 11:41

import django.db.models.deletion
import template_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('document_type', models.CharField(choices=[('PUB', 'Microsoft Publisher (.pub)'), ('PDF', 'PDF Document'), ('XLS', 'Excel Spreadsheet'), ('DOC', 'Word Document'), ('PPT', 'PowerPoint Presentation'), ('JPG', 'JPEG Image'), ('PNG', 'PNG Image'), ('PSD', 'Photoshop File'), ('AI', 'Adobe Illustrator'), ('OTHER', 'Other Format')], max_length=10)),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210×297 mm)'), ('A3', 'A3 (297×420 mm)'), ('A5', 'A5 (148×210 mm)'), ('LETTER', 'Letter (8.5×11 in)'), ('LEGAL', 'Legal (8.5×14 in)'), ('BUSINESS', 'Business Card'), ('BANNER', 'Banner'), ('CUSTOM', 'Custom Size')], max_length=20)),
                ('template_category', models.CharField(choices=[('WEDDING', 'Wedding Cards'), ('BUSINESS', 'Business Cards'), ('BANNERS', 'Banners & Posters'), ('STICKERS', 'Stickers & Labels'), ('INVITATIONS', 'Invitation Cards'), ('CERTIFICATES', 'Certificates'), ('FLYERS', 'Flyers & Brochures'), ('LETTERHEADS', 'Letterheads'), ('RECEIPTS', 'Receipts & Invoices'), ('OTHER', 'Other Templates')], max_length=20)),
                ('file', models.FileField(upload_to=template_manager.models.template_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='template_manager.category')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_templates', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='template_manager.templatedocument')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='template_manager.templatedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='templatedocument',
            index=models.Index(fields=['title'], name='template_ma_title_b2247d_idx'),
        ),
        migrations.AddIndex(
            model_name='templatedocument',
            index=models.Index(fields=['document_type'], name='template_ma_documen_8ae77d_idx'),
        ),
        migrations.AddIndex(
            model_name='templatedocument',
            index=models.Index(fields=['paper_size'], name='template_ma_paper_s_fdecce_idx'),
        ),
        migrations.AddIndex(
            model_name='templatedocument',
            index=models.Index(fields=['template_category'], name='template_ma_templat_626340_idx'),
        ),
        migrations.AddIndex(
            model_name='templatedocument',
            index=models.Index(fields=['is_verified'], name='template_ma_is_veri_bac354_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templaterating',
            unique_together={('template', 'user')},
        ),
    ]
