# Generated by Django 5.2.6 on 2025-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedocument',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
