# Generated by Django 5.2.6 on 2025-10-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_manager', '0002_templatedocument_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template_link',
            field=models.URLField(blank=True, help_text='Optional: Link to template (Canvas, Google Docs, etc.)'),
        ),
    ]
